//! elog dispatch.
//!
//! After a transaction completes, the build-time elog messages aggregated on the
//! [`TransactionReport`](moraine_install::TransactionReport) are dispatched to the
//! modules named in `PORTAGE_ELOG_SYSTEM`, each filtered by its own level classes
//! (the `name:levels` colon override) or by `PORTAGE_ELOG_CLASSES` when it has no
//! override. Two modules are implemented: `save_summary` (append a per-package
//! block to `summary.log`) and `echo` (print a consolidated end-of-run summary).
//! Other module names are recognized but skipped with a notice.

use std::collections::BTreeSet;
use std::io::Write as _;
use std::path::Path;

use moraine_install::PackageElog;

/// The default elog classes shipped in make.globals.
const DEFAULT_CLASSES: &str = "log warn error";
/// The default elog system shipped in make.globals.
const DEFAULT_SYSTEM: &str = "save_summary:log,warn,error,qa echo";

/// A configured elog module and the level classes it accepts.
struct ElogModule {
    name: String,
    levels: BTreeSet<String>,
}

/// Parse `PORTAGE_ELOG_CLASSES`/`PORTAGE_ELOG_SYSTEM` into modules with resolved
/// level sets, applying the `name:levels` override and defaulting to the classes.
fn parse_modules(classes: &str, system: &str) -> Vec<ElogModule> {
    let default_levels: BTreeSet<String> = classes.split_whitespace().map(str::to_owned).collect();
    system
        .split_whitespace()
        .map(|token| match token.split_once(':') {
            Some((name, levels)) => ElogModule {
                name: name.to_owned(),
                levels: levels.split(',').map(str::to_owned).collect(),
            },
            None => ElogModule {
                name: token.to_owned(),
                levels: default_levels.clone(),
            },
        })
        .collect()
}

/// Dispatch the aggregated elog through the configured modules. A no-op when
/// there are no messages.
pub fn dispatch(elog: &[PackageElog], classes: Option<&str>, system: Option<&str>, eroot: &Path) {
    if elog.is_empty() {
        return;
    }
    let classes = classes
        .filter(|s| !s.trim().is_empty())
        .unwrap_or(DEFAULT_CLASSES);
    let system = system
        .filter(|s| !s.trim().is_empty())
        .unwrap_or(DEFAULT_SYSTEM);
    for module in parse_modules(classes, system) {
        match module.name.as_str() {
            "save_summary" => save_summary(elog, &module.levels, eroot),
            "echo" => echo(elog, &module.levels),
            other => tracing::info!("elog module `{other}` is not implemented; skipping"),
        }
    }
}

/// The messages of one package matching the module's level set.
fn filtered<'a>(
    pkg: &'a PackageElog,
    levels: &BTreeSet<String>,
) -> Vec<&'a moraine_merge::ElogRecord> {
    pkg.messages
        .iter()
        .filter(|m| levels.contains(&m.level))
        .collect()
}

/// Append a per-package block of matching messages to
/// `${EROOT}/var/log/portage/elog/summary.log`, creating the directory if absent.
fn save_summary(elog: &[PackageElog], levels: &BTreeSet<String>, eroot: &Path) {
    let mut out = String::new();
    for pkg in elog {
        let messages = filtered(pkg, levels);
        if messages.is_empty() {
            continue;
        }
        out.push_str(&format!(
            ">>> Messages generated by process for package {}:\n",
            pkg.cpv
        ));
        for m in messages {
            out.push_str(&format!(
                "{}: {} ({})\n",
                m.level.to_uppercase(),
                m.text,
                m.phase
            ));
        }
        out.push('\n');
    }
    if out.is_empty() {
        return;
    }
    let dir = eroot.join("var/log/portage/elog");
    if let Err(e) = std::fs::create_dir_all(&dir) {
        tracing::warn!(error = %e, "could not create elog directory");
        return;
    }
    let path = dir.join("summary.log");
    match std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&path)
    {
        Ok(mut file) => {
            if let Err(e) = file.write_all(out.as_bytes()) {
                tracing::warn!(error = %e, "could not write elog summary");
            }
        }
        Err(e) => tracing::warn!(error = %e, "could not open elog summary"),
    }
}

/// Print a consolidated per-package summary of matching messages.
fn echo(elog: &[PackageElog], levels: &BTreeSet<String>) {
    for pkg in elog {
        let messages = filtered(pkg, levels);
        if messages.is_empty() {
            continue;
        }
        println!("\n>>> Messages for package {}:", pkg.cpv);
        for m in messages {
            println!(" {} {}", marker(&m.level), m.text);
        }
    }
}

/// The einfo-style line marker for an elog class.
fn marker(level: &str) -> &'static str {
    match level {
        "warn" | "qa" => "*W",
        "error" => "*E",
        _ => "*",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use moraine_merge::ElogRecord;

    fn rec(level: &str, text: &str) -> ElogRecord {
        ElogRecord {
            level: level.to_owned(),
            phase: "install".to_owned(),
            text: text.to_owned(),
        }
    }

    #[test]
    fn module_parsing_applies_colon_override_and_default() {
        let modules = parse_modules("log warn error", "save_summary:log,warn,error,qa echo");
        assert_eq!(modules.len(), 2);
        assert_eq!(modules[0].name, "save_summary");
        assert!(modules[0].levels.contains("qa"));
        assert_eq!(modules[1].name, "echo");
        // echo has no override, so it uses the default classes (no qa).
        assert!(!modules[1].levels.contains("qa"));
        assert!(modules[1].levels.contains("warn"));
    }

    #[test]
    fn save_summary_appends_filtered_block() {
        let tmp = tempfile::tempdir().unwrap();
        let elog = vec![PackageElog {
            cpv: "dev-libs/foo-1".to_owned(),
            messages: vec![rec("warn", "a warning"), rec("info", "an info note")],
        }];
        let levels: BTreeSet<String> = ["log", "warn", "error"]
            .into_iter()
            .map(str::to_owned)
            .collect();
        save_summary(&elog, &levels, tmp.path());
        let summary =
            std::fs::read_to_string(tmp.path().join("var/log/portage/elog/summary.log")).unwrap();
        assert!(summary.contains("dev-libs/foo-1"));
        assert!(summary.contains("WARN: a warning"));
        // The info message is filtered out by the level set.
        assert!(!summary.contains("an info note"));
    }
}
