//! elog dispatch.
//!
//! After a transaction completes, the build-time elog messages aggregated on the
//! [`TransactionReport`](moraine_install::TransactionReport) are dispatched to the
//! modules named in `PORTAGE_ELOG_SYSTEM`, each filtered by its own level classes
//! (the `name:levels` colon override) or by `PORTAGE_ELOG_CLASSES` when it has no
//! override. The implemented modules are `save_summary` (append a per-package
//! block to `summary.log`), `save` (one timestamped log file per package),
//! `syslog` (emit each message to the system log under facility `local5`),
//! `custom` (write the per-package log, then run `PORTAGE_ELOG_COMMAND`), and
//! `echo` (print a consolidated end-of-run summary). The `mail` and
//! `mail_summary` modules remain deferred and are skipped with a notice.

use std::collections::BTreeSet;
use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use moraine_install::PackageElog;
use moraine_merge::ElogRecord;

/// The default elog classes shipped in make.globals.
const DEFAULT_CLASSES: &str = "log warn error";
/// The default elog system shipped in make.globals.
const DEFAULT_SYSTEM: &str = "save_summary:log,warn,error,qa echo";

/// A configured elog module and the level classes it accepts. The level set is
/// stored upper-cased so the per-message comparison matches `filter_loglevels`.
struct ElogModule {
    name: String,
    levels: BTreeSet<String>,
}

/// Parse `PORTAGE_ELOG_CLASSES`/`PORTAGE_ELOG_SYSTEM` into modules with resolved
/// level sets, applying the `name:levels` override and defaulting to the classes.
/// Level sets are upper-cased once here, preserving the `*` wildcard token.
fn parse_modules(classes: &str, system: &str) -> Vec<ElogModule> {
    let default_levels: BTreeSet<String> =
        classes.split_whitespace().map(str::to_uppercase).collect();
    system
        .split_whitespace()
        .map(|token| match token.split_once(':') {
            Some((name, levels)) => ElogModule {
                name: name.to_owned(),
                levels: levels.split(',').map(str::to_uppercase).collect(),
            },
            None => ElogModule {
                name: token.to_owned(),
                levels: default_levels.clone(),
            },
        })
        .collect()
}

/// Dispatch the aggregated elog through the configured modules. A no-op when
/// there are no messages.
pub fn dispatch(
    elog: &[PackageElog],
    classes: Option<&str>,
    system: Option<&str>,
    command: Option<&str>,
    eroot: &Path,
) {
    if elog.is_empty() {
        return;
    }
    let classes = classes
        .filter(|s| !s.trim().is_empty())
        .unwrap_or(DEFAULT_CLASSES);
    let system = system
        .filter(|s| !s.trim().is_empty())
        .unwrap_or(DEFAULT_SYSTEM);
    for module in parse_modules(classes, system) {
        match module.name.as_str() {
            "save_summary" => save_summary(elog, &module.levels, eroot),
            "save" => save(elog, &module.levels, eroot),
            "syslog" => syslog(elog, &module.levels),
            "custom" => custom(elog, &module.levels, command, eroot),
            "echo" => echo(elog, &module.levels),
            other => tracing::info!("elog module `{other}` is not implemented; skipping"),
        }
    }
}

/// The messages of one package matching the module's level set.
///
/// The configured level set is already upper-cased; the message level is
/// upper-cased here and a set containing `*` retains every message, matching
/// `lib/portage/elog/filtering.py:filter_loglevels`.
fn filtered<'a>(pkg: &'a PackageElog, levels: &BTreeSet<String>) -> Vec<&'a ElogRecord> {
    let all = levels.contains("*");
    pkg.messages
        .iter()
        .filter(|m| all || levels.contains(&m.level.to_uppercase()))
        .collect()
}

/// Format one package's filtered messages into a `summary.log`-style block.
fn package_block(cpv: &str, messages: &[&ElogRecord]) -> String {
    let mut out = format!(">>> Messages generated by process for package {cpv}:\n");
    for m in messages {
        out.push_str(&format!(
            "{}: {} ({})\n",
            m.level.to_uppercase(),
            m.text,
            m.phase
        ));
    }
    out.push('\n');
    out
}

/// Append a per-package block of matching messages to
/// `${EROOT}/var/log/portage/elog/summary.log`, creating the directory if absent.
fn save_summary(elog: &[PackageElog], levels: &BTreeSet<String>, eroot: &Path) {
    let mut out = String::new();
    for pkg in elog {
        let messages = filtered(pkg, levels);
        if messages.is_empty() {
            continue;
        }
        out.push_str(&package_block(&pkg.cpv, &messages));
    }
    if out.is_empty() {
        return;
    }
    let dir = eroot.join("var/log/portage/elog");
    if let Err(e) = std::fs::create_dir_all(&dir) {
        tracing::warn!(error = %e, "could not create elog directory");
        return;
    }
    let path = dir.join("summary.log");
    match std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&path)
    {
        Ok(mut file) => {
            if let Err(e) = file.write_all(out.as_bytes()) {
                tracing::warn!(error = %e, "could not write elog summary");
            }
        }
        Err(e) => tracing::warn!(error = %e, "could not open elog summary"),
    }
}

/// Write one package's filtered messages to a per-package timestamped log under
/// `${EROOT}/var/log/portage/elog/${cat}:${pf}:${YYYYMMDD-HHMMSS}.log`, returning
/// the file path on success. Mirrors `lib/portage/elog/mod_save.py:process`.
fn write_package_log(eroot: &Path, cpv: &str, body: &str) -> Option<PathBuf> {
    let (cat, pf) = cpv.split_once('/').unwrap_or(("", cpv));
    let dir = eroot.join("var/log/portage/elog");
    if let Err(e) = std::fs::create_dir_all(&dir) {
        tracing::warn!(error = %e, "could not create elog directory");
        return None;
    }
    let stamp = utc_timestamp(SystemTime::now());
    let path = dir.join(format!("{cat}:{pf}:{stamp}.log"));
    match std::fs::write(&path, body) {
        Ok(()) => Some(path),
        Err(e) => {
            tracing::warn!(error = %e, "could not write per-package elog file");
            None
        }
    }
}

/// Write one timestamped log file per package holding its filtered messages.
fn save(elog: &[PackageElog], levels: &BTreeSet<String>, eroot: &Path) {
    for pkg in elog {
        let messages = filtered(pkg, levels);
        if messages.is_empty() {
            continue;
        }
        let body = package_block(&pkg.cpv, &messages);
        write_package_log(eroot, &pkg.cpv, &body);
    }
}

/// Emit each filtered message to the system log via `logger`, one line per
/// message as `${cpv}: ${phase}: ${text}` under facility `local5`, identity
/// `portage`, at the priority mapped from the level. Mirrors
/// `lib/portage/elog/mod_syslog.py`. A missing `logger` degrades to a warning.
fn syslog(elog: &[PackageElog], levels: &BTreeSet<String>) {
    let mut missing = false;
    for pkg in elog {
        for m in filtered(pkg, levels) {
            let priority = syslog_priority(&m.level);
            let line = format!("{}: {}: {}", pkg.cpv, m.phase, m.text);
            let result = std::process::Command::new("logger")
                .arg("-p")
                .arg(format!("local5.{priority}"))
                .arg("-t")
                .arg("portage")
                .arg("--")
                .arg(line.trim_end_matches('\n'))
                .status();
            if result.is_err() && !missing {
                missing = true;
                tracing::warn!("`logger` is unavailable; skipping the syslog elog module");
            }
        }
    }
}

/// The syslog priority keyword for an elog level, matching `mod_syslog.py:_pri`.
fn syslog_priority(level: &str) -> &'static str {
    match level.to_uppercase().as_str() {
        "INFO" => "info",
        "WARN" | "QA" => "warning",
        "ERROR" => "err",
        _ => "notice",
    }
}

/// Write each package's per-package log, then run `PORTAGE_ELOG_COMMAND` with
/// `${LOGFILE}` and `${PACKAGE}` substituted. Skips with a warning when the
/// command is unset. Mirrors `lib/portage/elog/mod_custom.py:process`.
fn custom(elog: &[PackageElog], levels: &BTreeSet<String>, command: Option<&str>, eroot: &Path) {
    let Some(command) = command.filter(|s| !s.trim().is_empty()) else {
        tracing::warn!("PORTAGE_ELOG_COMMAND is not defined; skipping the custom elog module");
        return;
    };
    for pkg in elog {
        let messages = filtered(pkg, levels);
        if messages.is_empty() {
            continue;
        }
        let body = package_block(&pkg.cpv, &messages);
        let Some(logfile) = write_package_log(eroot, &pkg.cpv, &body) else {
            continue;
        };
        let cmd = command
            .replace("${LOGFILE}", &logfile.to_string_lossy())
            .replace("${PACKAGE}", &pkg.cpv);
        match std::process::Command::new("sh")
            .arg("-c")
            .arg(&cmd)
            .status()
        {
            Ok(status) if status.success() => {}
            Ok(status) => {
                tracing::warn!(
                    status = status.code(),
                    "PORTAGE_ELOG_COMMAND reported failure"
                )
            }
            Err(e) => tracing::warn!(error = %e, "could not run PORTAGE_ELOG_COMMAND"),
        }
    }
}

/// Print a consolidated per-package summary of matching messages.
fn echo(elog: &[PackageElog], levels: &BTreeSet<String>) {
    for pkg in elog {
        let messages = filtered(pkg, levels);
        if messages.is_empty() {
            continue;
        }
        println!("\n>>> Messages for package {}:", pkg.cpv);
        for m in messages {
            println!(" {} {}", marker(&m.level), m.text);
        }
    }
}

/// The einfo-style line marker for an elog class.
fn marker(level: &str) -> &'static str {
    match level.to_lowercase().as_str() {
        "warn" | "qa" => "*W",
        "error" => "*E",
        _ => "*",
    }
}

/// Format a `SystemTime` as a `YYYYMMDD-HHMMSS` UTC timestamp, matching
/// `time.strftime("%Y%m%d-%H%M%S", time.gmtime(...))` in `mod_save.py`.
fn utc_timestamp(now: SystemTime) -> String {
    let secs = now
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0);
    let days = secs.div_euclid(86_400);
    let rem = secs.rem_euclid(86_400);
    let (hour, minute, second) = (rem / 3_600, (rem % 3_600) / 60, rem % 60);
    let (year, month, day) = civil_from_days(days);
    format!("{year:04}{month:02}{day:02}-{hour:02}{minute:02}{second:02}")
}

/// The civil date `(year, month, day)` for a count of days since the Unix epoch,
/// via Howard Hinnant's `civil_from_days` algorithm (the inverse of the
/// `days_from_civil` helper in `moraine-sync`).
fn civil_from_days(days: i64) -> (i64, u32, u32) {
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let day = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let month = (if mp < 10 { mp + 3 } else { mp - 9 }) as u32;
    let year = if month <= 2 { y + 1 } else { y };
    (year, month, day)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rec(level: &str, text: &str) -> ElogRecord {
        ElogRecord {
            level: level.to_owned(),
            phase: "install".to_owned(),
            text: text.to_owned(),
        }
    }

    #[test]
    fn module_parsing_applies_colon_override_and_default() {
        let modules = parse_modules("log warn error", "save_summary:log,warn,error,qa echo");
        assert_eq!(modules.len(), 2);
        assert_eq!(modules[0].name, "save_summary");
        // Level sets are stored upper-cased.
        assert!(modules[0].levels.contains("QA"));
        assert_eq!(modules[1].name, "echo");
        // echo has no override, so it uses the default classes (no qa).
        assert!(!modules[1].levels.contains("QA"));
        assert!(modules[1].levels.contains("WARN"));
    }

    #[test]
    fn filtering_is_case_insensitive_and_honors_wildcard() {
        let pkg = PackageElog {
            cpv: "dev-libs/foo-1".to_owned(),
            messages: vec![rec("warn", "w"), rec("info", "i")],
        };
        // A lower-case `info` message matches an upper-cased `INFO` class.
        let levels: BTreeSet<String> = ["INFO"].into_iter().map(str::to_owned).collect();
        let got = filtered(&pkg, &levels);
        assert_eq!(got.len(), 1);
        assert_eq!(got[0].text, "i");
        // The `*` wildcard retains every message.
        let star: BTreeSet<String> = ["*"].into_iter().map(str::to_owned).collect();
        assert_eq!(filtered(&pkg, &star).len(), 2);
    }

    #[test]
    fn save_summary_appends_filtered_block() {
        let tmp = tempfile::tempdir().unwrap();
        let elog = vec![PackageElog {
            cpv: "dev-libs/foo-1".to_owned(),
            messages: vec![rec("warn", "a warning"), rec("info", "an info note")],
        }];
        let levels: BTreeSet<String> = ["LOG", "WARN", "ERROR"]
            .into_iter()
            .map(str::to_owned)
            .collect();
        save_summary(&elog, &levels, tmp.path());
        let summary =
            std::fs::read_to_string(tmp.path().join("var/log/portage/elog/summary.log")).unwrap();
        assert!(summary.contains("dev-libs/foo-1"));
        assert!(summary.contains("WARN: a warning"));
        // The info message is filtered out by the level set.
        assert!(!summary.contains("an info note"));
    }

    #[test]
    fn save_writes_one_timestamped_file_per_package() {
        let tmp = tempfile::tempdir().unwrap();
        let elog = vec![PackageElog {
            cpv: "dev-libs/foo-1".to_owned(),
            messages: vec![rec("warn", "a warning")],
        }];
        let levels: BTreeSet<String> = ["WARN"].into_iter().map(str::to_owned).collect();
        save(&elog, &levels, tmp.path());
        let dir = tmp.path().join("var/log/portage/elog");
        let files: Vec<_> = std::fs::read_dir(&dir)
            .unwrap()
            .flatten()
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .collect();
        assert_eq!(files.len(), 1);
        let name = &files[0];
        // Named `${cat}:${pf}:${stamp}.log`.
        assert!(name.starts_with("dev-libs:foo-1:"));
        assert!(name.ends_with(".log"));
        let body = std::fs::read_to_string(dir.join(name)).unwrap();
        assert!(body.contains("WARN: a warning"));
    }

    #[test]
    fn utc_timestamp_formats_known_epoch() {
        // 2021-01-01 00:00:00 UTC.
        let when = UNIX_EPOCH + std::time::Duration::from_secs(1_609_459_200);
        assert_eq!(utc_timestamp(when), "20210101-000000");
        // The Unix epoch itself.
        assert_eq!(utc_timestamp(UNIX_EPOCH), "19700101-000000");
    }

    #[test]
    fn syslog_priority_maps_levels() {
        assert_eq!(syslog_priority("info"), "info");
        assert_eq!(syslog_priority("WARN"), "warning");
        assert_eq!(syslog_priority("qa"), "warning");
        assert_eq!(syslog_priority("error"), "err");
        assert_eq!(syslog_priority("log"), "notice");
    }
}
