//! End-to-end test of the ebuild metadata generator against a real repository
//! tree and a real `bash`. An overlay ebuild with no `metadata/md5-cache` that
//! inherits an eclass is regenerated by sourcing it, and a second generation
//! reuses the entry unchanged. Skipped when `bash` is unavailable.

use std::process::Command;

use moraine_cli::regen::EbuildMetadataGenerator;
use moraine_repo::discover;
use moraine_sync::MetadataGenerator;

fn bash_available() -> bool {
    Command::new("bash")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

#[test]
fn overlay_ebuild_without_cache_is_regenerated_then_reused() {
    if !bash_available() {
        return;
    }
    let tmp = tempfile::tempdir().unwrap();
    let loc = tmp.path().join("gentoo");
    std::fs::create_dir_all(loc.join("profiles")).unwrap();
    std::fs::write(loc.join("profiles/repo_name"), "gentoo\n").unwrap();

    // An eclass contributing IUSE and DEPEND, and an ebuild that inherits it.
    std::fs::create_dir_all(loc.join("eclass")).unwrap();
    std::fs::write(
        loc.join("eclass/foo.eclass"),
        "IUSE=\"ssl\"\nDEPEND=\"dev-libs/libfoo\"\n",
    )
    .unwrap();
    let pkg_dir = loc.join("dev-libs/pkg");
    std::fs::create_dir_all(&pkg_dir).unwrap();
    std::fs::write(
        pkg_dir.join("pkg-1.ebuild"),
        "EAPI=8\ninherit foo\nDESCRIPTION=\"t\"\nSLOT=0/2\nKEYWORDS=\"amd64\"\nIUSE=\"threads\"\n",
    )
    .unwrap();

    let conf = tmp.path().join("repos.conf");
    std::fs::write(&conf, format!("[gentoo]\nlocation = {}\n", loc.display())).unwrap();
    let set = discover(&conf).unwrap();

    let generator = EbuildMetadataGenerator::new(&set).expect("generator");

    // First generation sources the ebuild (no cache exists).
    let first = generator
        .generate("gentoo", "dev-libs/pkg-1", None)
        .expect("regenerated entry");
    assert!(
        first.regenerated,
        "first generation should source the ebuild"
    );
    let entry = first.entry;
    assert_eq!(entry.category, "dev-libs");
    assert_eq!(entry.package, "pkg");
    assert_eq!(entry.version, "1");
    assert_eq!(entry.eapi, "8");
    assert_eq!(entry.slot, "0");
    assert_eq!(entry.subslot.as_deref(), Some("2"));
    assert_eq!(entry.depend, "dev-libs/libfoo");
    assert!(entry.inherited.contains(&"foo".to_string()));
    // IUSE folds the eclass and ebuild contributions.
    assert!(entry.iuse.contains(&"ssl".to_string()));
    assert!(entry.iuse.contains(&"threads".to_string()));
    assert!(!entry.md5.is_empty(), "provenance stamp recorded");

    // Second generation with the prior entry reuses it without sourcing.
    let second = generator
        .generate("gentoo", "dev-libs/pkg-1", Some(&entry))
        .expect("reused entry");
    assert!(!second.regenerated, "unchanged entry should be reused");
    assert_eq!(second.entry.depend, "dev-libs/libfoo");

    // Changing the eclass invalidates the stamp and forces regeneration.
    std::fs::write(
        loc.join("eclass/foo.eclass"),
        "IUSE=\"ssl\"\nDEPEND=\"dev-libs/libfoo dev-libs/extra\"\n",
    )
    .unwrap();
    let third = generator
        .generate("gentoo", "dev-libs/pkg-1", Some(&entry))
        .expect("regenerated after eclass change");
    assert!(third.regenerated, "eclass change should force regeneration");
    assert_eq!(third.entry.depend, "dev-libs/libfoo dev-libs/extra");
}
